version = 1
disable_existing_loggers = false

[formatters.simple]
style = '{'
format = '[{levelname}] {message}'

[formatters.detailed]
'()' = 'src.coh2_live_stats.util.CustomFormatter'
style = '{'
format = '[{levelname:<5}] [{asctime}] [{taskName:<7}] [{name} {module}:{lineno}:{funcName}] - {message}'
datefmt = '%Y-%m-%dT%H:%M:%S.%f%z'

[handlers.stderr]
class = 'logging.StreamHandler'
level = 'WARNING'
formatter = 'simple'
stream = 'ext://sys.stderr'

[handlers.file]
class = 'logging.handlers.RotatingFileHandler'
level = 'DEBUG'
formatter = 'detailed'
filename = 'coh2livestats.log'
maxBytes = 500000
backupCount = 3
encoding = 'utf-8'

[handlers.queue_handler]
class = 'logging.handlers.QueueHandler'
handlers = ['stderr', 'file']
respect_handler_level = true

[loggers.root]
level = 'WARNING'
handlers = ['queue_handler']

[loggers.coh2_live_stats]
level = 'DEBUG'
