[build-system]
requires = ["setuptools >= 61.0", "setuptools-scm >= 8"]
build-backend = "setuptools.build_meta"

[project]
name = "coh2_live_stats"
dynamic = ["version"]
dependencies = [
    "httpx >= 0.27.0",
    "prettytable >= 3.10.0",
    "pydantic-settings >= 2.2.1",
    "watchdog >= 4.0.0",
]
requires-python = ">= 3.12"
authors = [
    { name = "Andreas Becker", email = "brofi.archlinux@gmail.com" },
]
description = "Shows player stats of a currently or last played or viewed CoH2 game"
readme = "README.md"
license = { file = "COPYING" }
keywords = ["CoH2", "Company of Heroes 2"]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Games/Entertainment :: Real Time Strategy"
]

# No better solution for this yet (https://peps.python.org/pep-0735/)
[project.optional-dependencies]
dev = [
    "ruff >= 0.3.5",
    "pre-commit >= 3.7.0",
]
build = [
    "build >= 1.2.1",
    "invoke >= 2.2.0",
    "pyinstaller >= 6.5.0",
    "tomlkit >= 0.12.4",
]

[project.scripts]
coh2livestats = "coh2_live_stats.__main__:run"

[tool.setuptools.package-data]
coh2_live_stats = ["*.toml"]
"coh2_live_stats.res" = ["*.wav"]

[tool.setuptools_scm]
version_file = "src/coh2_live_stats/version.py"

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", "W", # pycodestyle
    "I", # isort
    "N", # pep8-naming
    "FBT", # flake8-boolean-trap
    "B", # flake8-bugbear
    "COM", # flake8-commas
    "RET", # flake8-return
    "SIM", # flake8-simplify
]
ignore = [
    "E501", # fomatter sometimes allows code to exceed 'line-length'
    "COM812", # conflicts with formatter
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
classes = ["URL"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "preserve"
skip-magic-trailing-comma = true
