[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coh2_live_stats"
version = "1.3.2"
dependencies = [
    "httpx",
    "prettytable",
    "requests",
    "watchdog",
]
requires-python = ">=3.11"
authors = [
    { name = "Andreas Becker", email = "brofi.archlinux@gmail.com" },
]
description = "Shows player stats of a currently or last played or viewed CoH2 game"
readme = "README.md"
license = { file = "COPYING" }
keywords = ["CoH2", "Company of Heroes 2"]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Games/Entertainment :: Real Time Strategy"
]
[project.scripts]
coh2livestats = "coh2_live_stats.__main__:run"

[tool.setuptools.package-data]
coh2_live_stats = ["*.toml"]
"coh2_live_stats.res" = ["notify.wav"]
