# Configuration file for CoH2LiveStats.
#
# Valid configuration file paths in order of detection:
#   * %USERPROFILE%\CONFIG
#   * PARENT_FOLDER_OF_EXECUTABLE\CONFIG
# with CONFIG in:
#   * _coh2livestats.toml
#   * .coh2livestats.toml
#   * coh2livestats.toml
#   * _coh2_live_stats.toml
#   * .coh2_live_stats.toml
#   * coh2_live_stats.toml
#
# Valid colors (case-insensitive):
#   * black, red, green, yellow, blue, magenta, cyan, white
#   * bright_black, bright_red, bright_green, bright_yellow, bright_blue, bright_magenta, bright_cyan, bright_white

# Path to observed Company of Heroes 2 log file. Supports OS environment variables.
# logfile = '%USERPROFILE%\Documents\My Games\Company of Heroes 2\warnings.log'

#[notification]
# Whether to play a notification sound.
#sound = true
# Custom waveform audio file for notification sound.
#wavfile = ''

# Output table options.
#[table]
# Wether to use color at all.
#color = true
# Draw a border around the output table. Can cause issues with CJK characters.
#border = false

# Output table color options.
#[table.colors]
#border = 'bright_black'
#label = 'bright_black'

# Player-specific color options.
#[table.colors.player]
#high_drop_rate = 'red'
# Color for highest ranked player and high winrate.
#high = 'bright_white'
# Color for lowest ranked player and low winrate.
#low = 'bright_black'

# Faction colors.
#[table.colors.faction]
# Wehrmacht
#wm = 'red'
# Soviet Union
#su = 'red'
# Oberkommando West
#okw = 'cyan'
# US Forces
#us = 'blue'
# British Forces
#uk = 'yellow'
