# Configuration file for CoH2LiveStats
# 
# Generated 2024-03-30 05:30:47
# Version 1.9.1.dev1+g3ebc4f7
# 
# Valid config locations:
#     * %USERPROFILE%
#     * Next to executable
# Valid config names:
#     * _coh2livestats.toml
#     * .coh2livestats.toml
#     * coh2livestats.toml
#     * _coh2_live_stats.toml
#     * .coh2_live_stats.toml
#     * coh2_live_stats.toml
# 
# Valid colors:
#     * 'black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan' or 'white'
#     * 'bright_black', 'bright_red', 'bright_green', 'bright_yellow', 'bright_blue', 'bright_magenta', 'bright_cyan' or 'bright_white'
# 
# Valid sound values:
#     * 'horn_subtle', 'horn' or 'horn_epic'
#     * Path to custom WAV file
# 
# Valid alignment values: 'l', 'c' or 'r'
# 
# Notes:
#     * CJK characters can distort table (table.border = false and name column last is recommended)


logfile = "%USERPROFILE%\\Documents\\My Games\\Company of Heroes 2\\warnings.log" # Path to observed Company of Heroes 2 log file (supports OS environment variables)

[notification] # Notification sound options
play_sound = true # Play a notification sound when a new multiplayer match was found
sound = "%USERPROFILE%\\PycharmProjects\\CoH2LiveStats\\src\\coh2_live_stats\\res\\horn.wav" # Built-in notification sound name or full path to custom waveform audio file

[table] # Output table options
color = true # Use color for output
border = false # Draw a border around the output table
show_average = true # Show team's average rank and level
always_show_team = false # Always show team columns, even if they're empty
drop_ratio_high_threshold = 0.05 # Drop ratios are considered high if they're higher than or equal this value (used for color)
win_ratio_high_threshold = 0.6 # Win ratios are considered high if they're higher than or equal this value (used for color)
win_ratio_low_threshold = 0.5 # Win ratios are considered low if they're lower than this value (used for color)

[table.colors] # Output table color options
border = "BRIGHT_BLACK" # Output table border color
label = "BRIGHT_BLACK" # Output table header color

[table.colors.player] # Player-specific color options
high_drop_rate = "RED" # Color for a high player drop ratio
high = "BRIGHT_WHITE" # Color for highest ranked player and high win ratio
low = "BRIGHT_BLACK" # Color for lowest ranked player and low win ratio


[table.colors.faction] # Faction colors
wm = "RED" # Wehrmacht color
su = "RED" # Soviet Union color
okw = "CYAN" # Oberkommando West color
us = "BLUE" # US Forces color
uk = "YELLOW" # British Forces color


[table.columns] # Output table column options
[table.columns.faction]
visible = true
pos = 0
label = "Fac"
align = "l"


[table.columns.rank]
visible = true
pos = 0
label = "Rank"
align = "r"


[table.columns.level]
visible = true
pos = 0
label = "Lvl"
align = "r"


[table.columns.win_ratio]
visible = true
pos = 0
label = "W%"
align = "r"


[table.columns.drop_ratio]
visible = true
pos = 0
label = "D%"
align = "r"


[table.columns.team]
visible = true
pos = 0
label = "Team"
align = "c"


[table.columns.team_rank]
visible = true
pos = 0
label = "T_Rank"
align = "r"


[table.columns.team_level]
visible = true
pos = 0
label = "T_Level"
align = "r"


[table.columns.steam_profile]
visible = false
pos = 0
label = "Profile"
align = "l"


[table.columns.country]
visible = true
pos = 0
label = "Country"
align = "l"


[table.columns.name]
visible = true
pos = 0
label = "Name"
align = "l"
